### ISSUE TITLE
Error on EntityDeathEvent

### ISSUE THREAD

**Issue by flashpaul** [JoelGodOfwar/MoreMobHeads#11]
Hi, I try to kill a mob, in particular the Glow Squid:

VERSION:
(  -<[ PLEASE INCLUDE THIS WITH ANY ISSUE REPORTS ]>-
) This server is running Paper version git-Paper-364 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT)
(  vardebug=false debug=false in plugins\MoreMobHeads\config.yml
) jarfilename=\MoreMobHeads-1.15_1.0.33.jar
(  -<[ PLEASE INCLUDE THIS WITH ANY ISSUE REPORTS ]>-

ERROR: 
[15:23:28 ERROR]: Could not pass event EntityDeathEvent to MoreMobHeads v1.15_1.0.33
java.lang.NoClassDefFoundError: Could not initialize class com.github.joelgodofwar.mmh.MoreMobHeadsLib
        at com.github.joelgodofwar.mmh.handlers.EventHandler_1_20_R1.onEntityDeathEvent(EventHandler_1_20_R1.java:1677) ~[MoreMobHeads-1.15_1.0.33.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor481.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-364]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-364]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-364]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:959) ~[paper-1.20.4.jar:git-Paper-364]
        at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1836) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1730) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1555) ~[?:?]
        at net.minecraft.world.entity.animal.Squid.hurt(Squid.java:167) ~[?:?]
        at net.minecraft.world.entity.GlowSquid.hurt(GlowSquid.java:82) ~[paper-1.20.4.jar:git-Paper-364]
        at net.minecraft.world.entity.player.Player.attack(Player.java:1321) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2283) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$3.a(ServerGamePacketListenerImpl.java:2787) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2711) ~[?:?]
        at com.andavin.images.v1_20_R3.PlayerConnectionProxy.a(PlayerConnectionProxy.java:74) ~[images-2.3.2.jar:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-364]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1458) ~[paper-1.20.4.jar:git-Paper-364]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-364]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1435) ~[paper-1.20.4.jar:git-Paper-364]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1358) ~[paper-1.20.4.jar:git-Paper-364]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1336) ~[paper-1.20.4.jar:git-Paper-364]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[paper-1.20.4.jar:git-Paper-364]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-364]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

![image](https://github.com/JoelGodOfwar/MoreMobHeads/assets/44022635/a0f401f9-a630-4265-afdc-55afaefccd6b)

DEBUG MODE:
![image](https://github.com/JoelGodOfwar/MoreMobHeads/assets/44022635/39f6ea1b-1ed5-47b7-8377-03009a8cf86e)

**Comment by ghost** [comment]
This is also happening on my server whenever a head should drop.

**Comment by JoelGodOfwar** [comment]
1.15_1.0.33 is no longer supported, please update to 1.20_1.0.34.D16 or newer.
Available here https://discord.gg/PXN4bzT

**Comment by ghost** [comment]
C

> 1.15_1.0.33 is no longer supported, please update to 1.20_1.0.34.D16 or newer. Available here https://discord.gg/PXN4bzT

Could the newer version be uploaded to Spigot then? What is the official, publicly available release channel? (would be nice to see the plugin on a more modern platform such as Modrinth)

**Comment by JoelGodOfwar** [comment]
1.20_1.0.34 is currently in dev-build I'm looking to release it on SpigotMC and Bukkit possibly Friday.
Support including dev-builds are on Discord.

**Comment by ghost** [comment]
Ok, I will wait for the stable release then. Thanks!

**Comment by JoelGodOfwar** [comment]
1.20_1.0.34 stable has been released, closing this.
