### ISSUE TITLE
Exception when picking up blockhead and wrong name after placing

### ISSUE THREAD

**Issue by sqroot-1** [JoelGodOfwar/MoreMobHeads#2]
Got a stack of "Dried Kelp Block" from the wandering trader, placed and broke it.
The block now is no longer named "Dried Kelp Block" and when picking it up, an exception is fired.
I use Paper v298, no other plugins and the MoreMobHeads config.yml is untouched.
Log:
[10:52:58 INFO]: MoreMobHeads  1.14_1.0.11 [DEBUG] EPIE isPlayerEPIE=true
[10:52:58 INFO]: MoreMobHeads  1.14_1.0.11 [DEBUG] EPIE item.length=11
[10:52:58 INFO]: MoreMobHeads  1.14_1.0.11 [DEBUG] EPIE name=eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjgwNWNhZjNkMDJlMzVlNGFhZGMxOWFmMTVlODI3OTAxNzdmMWNkN2I3OWY0ZjViODhkOTQzYWM2YmUyMDNhMSJ9fX0=
[10:52:58 INFO]: MoreMobHeads  1.14_1.0.11 [DEBUG] EPIE lore=null
[10:52:58 INFO]: MoreMobHeads  1.14_1.0.11 [DEBUG] EPIE ownerName.lngth >= 40
[10:52:58 INFO]: MoreMobHeads  1.14_1.0.11 [DEBUG] EPIE mobname from texture=null
[10:52:58 ERROR]: Could not pass event EntityPickupItemEvent to MoreMobHeads v1.14_1.0.11
java.lang.NullPointerException: null
        at com.github.joelgodofwar.mmh.MoreMobHeads.OnTake(MoreMobHeads.java:1407) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor3.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-298]
        at org.bukkit.plugin.EventExecutor$$Lambda$2533/1278786085.execute(Unknown Source) ~[?:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-298]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-298]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-298]
        at net.minecraft.server.v1_15_R1.EntityItem.pickup(EntityItem.java:371) ~[patched_1.15.2.jar:git-Paper-298]
        at net.minecraft.server.v1_15_R1.EntityHuman.c(EntityHuman.java:492) ~[patched_1.15.2.jar:git-Paper-298]
        at net.minecraft.server.v1_15_R1.EntityHuman.movementTick(EntityHuman.java:465) ~[patched_1.15.2.jar:git-Paper-298]
        at net.minecraft.server.v1_15_R1.EntityLiving.tick(EntityLiving.java:2396) ~[patched_1.15.2.jar:git-Paper-298]
        at net.minecraft.server.v1_15_R1.EntityHuman.tick(EntityHuman.java:165) ~[patched_1.15.2.jar:git-Paper-298]
        at net.minecraft.server.v1_15_R1.EntityPlayer.playerTick(EntityPlayer.java:442) ~[patched_1.15.2.jar:git-Paper-298]
        at net.minecraft.server.v1_15_R1.PlayerConnection.tick(PlayerConnection.java:159) ~[patched_1.15.2.jar:git-Paper-298]
        at net.minecraft.server.v1_15_R1.NetworkManager.a(NetworkManager.java:343) ~[patched_1.15.2.jar:git-Paper-298]
        at net.minecraft.server.v1_15_R1.ServerConnection.c(ServerConnection.java:140) ~[patched_1.15.2.jar:git-Paper-298]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1344) ~[patched_1.15.2.jar:git-Paper-298]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-298]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1173) ~[patched_1.15.2.jar:git-Paper-298]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:962) ~[patched_1.15.2.jar:git-Paper-298]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]

**Comment by JoelGodOfwar** [comment]
The losing name thing is part of a Minecraft issue that NBT tag is lost on placing. I have a fix already for some heads to get fixed on pickup, but not all of them.
I thought I had the exception fixed in that version, maybe it was my last dev version that fixed it.
The exception issue will be fixed in the next update, which should come shortly.
